#!/usr/bin/env python3
"""
generate_strings.py
-------------------
Single source of truth for all Interval app translations.

Usage:
    python3 Localization/generate_strings.py

Reads translations.csv and writes .strings files into the correct lproj
directories for every language and both targets (Interval + CadenceWidget).

Adding a new language:
  1. Add a column in translations.csv (e.g. "it" for Italian)
  2. Fill in the translations
  3. Run this script

Adding a new string:
  1. Add a row in translations.csv
  2. Run this script
"""

import csv
import os
import re

# ── Config ────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
CSV_PATH     = os.path.join(SCRIPT_DIR, "translations.csv")

# Targets that get their own lproj directories
TARGETS = {
    "Interval":      os.path.join(PROJECT_ROOT, "Interval"),
    "CadenceWidget": os.path.join(PROJECT_ROOT, "CadenceWidget"),
}

# Widget-only string prefixes/keywords (only written to CadenceWidget target)
WIDGET_ONLY_KEYS = {
    "No pinned timers",
    "Pin timers in the app to see them here.",
    "Pinned Timers",
    "Quick-start your pinned timers.",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def escape(s):
    """Escape special characters for .strings format."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

def write_strings_file(path, entries):
    """Write a .strings file from a list of (key, value) tuples."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* Generated by Localization/generate_strings.py — edit translations.csv */\n\n")
        for key, value in entries:
            f.write(f'/* No comment provided by engineer. */\n')
            f.write(f'"{escape(key)}" = "{escape(value)}";\n\n')
    print(f"  wrote {os.path.relpath(path, PROJECT_ROOT)}")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    # Read CSV (skip comment lines starting with #)
    rows = []
    languages = []

    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if not row or row[0].startswith("#"):
                continue
            if i == 0 or row[0] == "key":
                # Header row
                languages = [lang.strip() for lang in row[1:]]
                continue
            if len(row) < 2:
                continue
            rows.append(row)

    print(f"Loaded {len(rows)} strings for languages: {', '.join(languages)}")

    # Build per-language entry lists
    for lang_idx, lang in enumerate(languages):
        if lang == "en":
            continue  # English is the source; write it too so iOS recognises it

        col = lang_idx + 1  # +1 because col 0 is the key

        main_entries   = []
        widget_entries = []

        for row in rows:
            key   = row[0].strip().strip('"')
            value = row[col].strip().strip('"') if col < len(row) else key

            if key in WIDGET_ONLY_KEYS:
                widget_entries.append((key, value))
            else:
                main_entries.append((key, value))
                widget_entries.append((key, value))  # widget gets everything too

        # Write Interval target
        interval_path = os.path.join(TARGETS["Interval"], f"{lang}.lproj", "Localizable.strings")
        write_strings_file(interval_path, main_entries)

        # Write CadenceWidget target
        widget_path = os.path.join(TARGETS["CadenceWidget"], f"{lang}.lproj", "Localizable.strings")
        write_strings_file(widget_path, widget_entries)

    # Also write English so iOS picks it up as an explicit localisation
    for lang_idx, lang in enumerate(languages):
        if lang != "en":
            continue
        col = lang_idx + 1

        main_entries   = []
        widget_entries = []

        for row in rows:
            key   = row[0].strip().strip('"')
            value = row[col].strip().strip('"') if col < len(row) else key

            if key in WIDGET_ONLY_KEYS:
                widget_entries.append((key, value))
            else:
                main_entries.append((key, value))
                widget_entries.append((key, value))

        interval_path = os.path.join(TARGETS["Interval"], "en.lproj", "Localizable.strings")
        write_strings_file(interval_path, main_entries)

        widget_path = os.path.join(TARGETS["CadenceWidget"], "en.lproj", "Localizable.strings")
        write_strings_file(widget_path, widget_entries)

    print("\nDone. Rebuild the app in Xcode to pick up the new strings.")
    print("To add French/Spanish: add 'fr' and 'es' lproj dirs in Xcode")
    print("(Project → Info → Localizations → +), then re-run this script.")

if __name__ == "__main__":
    main()
